name: Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
        with:
          run_install: true

      - name: Type check
        if: matrix.os == 'ubuntu-latest'
        run: pnpm type-check

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: pnpm lint
